name: Java Vector DB POC

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -d $HOME gradle-8.7-bin.zip
          export PATH=$HOME/gradle-8.7/bin:$PATH

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: gradle build